// <auto-generated />
namespace TheBattle.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class soldierName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(soldierName));
        
        string IMigrationMetadata.Id
        {
            get { return "201305141423280_soldierName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
