// <auto-generated />
namespace TheBattle.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class WeaponModelRenameColumnType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WeaponModelRenameColumnType));
        
        string IMigrationMetadata.Id
        {
            get { return "201305152136128_WeaponModelRenameColumnType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
