// <auto-generated />
namespace TheBattle.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SoldierArmyIsOptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SoldierArmyIsOptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201305161654098_SoldierArmyIsOptional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
